ALTER TABLE products
ADD COLUMN "buyPrice" BIGINT DEFAULT 0,
ADD COLUMN "retailPrice" BIGINT DEFAULT 0,
ADD COLUMN "resellerPrice" BIGINT DEFAULT 0,
ADD COLUMN barcode TEXT,
ADD COLUMN "supplierId" UUID REFERENCES suppliers(id),
ADD COLUMN "entryDate" TIMESTAMP WITH TIME ZONE DEFAULT NOW();