// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ejqhmtyqhjnijahmvluv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcWhtdHlxaGpuaWphaG12bHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDc4NTYsImV4cCI6MjA2OTIyMzg1Nn0.y5AXIhWiP3M3FG6pWECjMYC4E4HRiVJs7a0irMu9jWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);